name: 🧪 Run Automated Tests

on:
  push:
    - name: Run Tests and Generate Cucumber Report
      run: mvn clean verify

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 🔹 1. Faz o checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔹 2. Instala o Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 🔹 3. Compila e roda os testes
      - name: Run Cucumber Tests
        run: mvn clean test

      # 🔹 4. Gera o relatório do Cucumber
      - name: Generate Cucumber Report
        run: mvn verify

      # 🔹 5. Publica o relatório como artefato
      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-html-reports
