name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 🔹 Checkout do código
      - uses: actions/checkout@v4

      # 🔹 Configura o JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      # 🔹 Roda os testes
      - name: Run Tests
        run: mvn test

      # 🔹 Gera o relatório do Cucumber (se estiver configurado no pom.xml)
      - name: Generate Cucumber Report
        run: mvn verify

      # 🔹 Publica o relatório como artefato
      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-html-reports

      # 🔹 Build do pacote
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # 🔹 Publica no GitHub Packages
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
