name: 🧪 Run Automated Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 🔹 1. Faz o checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔹 2. Instala o Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 🔹 3. Compila e roda os testes
      - name: Run tests with Maven
        run: mvn clean test

      # 🔹 4. (Opcional) Publica os relatórios do Cucumber como artefato
      - name: Upload Cucumber HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-report.html
